### ISSUE TITLE
Live Preview

### ISSUE THREAD

**Issue by nolimits4web** [valnub/Framework7-Pure-Angular-Template#1]
Hi!

Can you upload it somewhere so i can post it in Examples section on F7 website?

**Comment by valnub** [comment]
Sure, I'll try to create a small demo and send you the link then

**Comment by valnub** [comment]
Here is the demo. Not much in there because it's just an empty template: http://www.timo-ernst.net/misc/f7-pure-angular-template-demo/

There is also another demo with some content based on this screencast: http://www.timo-ernst.net/blog/2015/11/05/video-screencast-how-to-use-framework7-with-angularjs/
The demo from the video is available here: http://www.timo-ernst.net/misc/f7-angular-screencast-demo/
