### ISSUE TITLE
question

### ISSUE THREAD

**Issue by okbeach** [valnub/Framework7-Pure-Angular-Template#14]
how to use route in f7 with angular?

**Comment by valnub** [comment]
Are you referring to Angular1 or Angular2+?

**Comment by okbeach** [comment]
Angular1.x

**Comment by okbeach** [comment]
I need your some example,thanks!

**Comment by valnub** [comment]
Hi,

Don't use Angular1 router - you should use router from F7: http://framework7.io/docs/router-api.html

However, since Angular1 is old, you shouldn't use it any more at all! Use Angular 2 or higher (currently version 4) instead. You can try this but I have no experience if this works or not: https://github.com/ashvin777/framework7.angular2

**Angular is no good fit for F7 anyway, as it is not officially supported.**

The best option is to use [Vue.js](https://vuejs.org/) with F7 as it is also very similar to Angular1 syntax-wise. Also it's dead-simple to use and currently very popular: http://framework7.io/vue/

If you really want to use Angular, then have a look at [Ionic](https://ionicframework.com/) or [OnsenUI](https://onsen.io/).
